### ISSUE TITLE
Share link with the encoded data

### ISSUE THREAD

**Issue by evermake** [InnoSWP/syntax-visualizer#11]
**User story:**
As a user, I want to get the link to the page with the encoded data so that I will be able to share or bookmark my code snippets with their AST and NCM representations
___
It would be great to share the link with the encoded into URL params data.

- [x] Decide which encoding to use for code compression (write 3 options and choose the best)
- [x] `code=`_encoded code_
- [x] `&lang=`_language ID_
- [x] `&parser=`_parser name_
- [x] Create `ShareLink` component

**Comment by metafates** [comment]
1. Use plain text (as encoded URI)
2. Convert text to bytes array with native TextEncoder interface in js
3. Use [lz-string](https://www.npmjs.com/package/lz-string) lib

I think lz-string is the best option here

**Comment by evermake** [comment]
4. base64

**Comment by evermake** [comment]
@metafates , how will you pass the encoded lz-string through URL params?

**Comment by metafates** [comment]
> @metafates , how will you pass the encoded lz-string through URL params?

Since it's just an int array I can join it with separator (like "-") and that's it

/?code=179-938-627-377... like that

**Comment by evermake** [comment]
<img width="550" alt="image" src="https://user-images.githubusercontent.com/53311479/174015180-ce40a291-4eba-43f0-8505-b8745f143ede.png">
You mean joining these LZ-string symbols?

**Comment by metafates** [comment]
> <img width="550" alt="image" src="https://user-images.githubusercontent.com/53311479/174015180-ce40a291-4eba-43f0-8505-b8745f143ede.png">
> 
> Do you mean joining these LZ-string symbols?

Yes, not int array, I think it's hex or something, anyways, it's easy to implement

**Comment by metafates** [comment]
Now I think about it - maybe it does take less bytes but overall length is longer, so maybe plain text is better🤔

**Comment by evermake** [comment]
Yes, the idea of compressing is that it generates a shorter string in the another encoding and if you transfer it using the initial one, you will only increase size :)

**Comment by metafates** [comment]
> Yes, the idea of compressing is that it generates a shorter string in the another encoding and if you transfer it using the initial one, you will only increase size :)


So, plain text?

**Comment by evermake** [comment]
I don't know the best option, it would be better if you get several code samples with different sizes (50 chars - 10000 chars) with different symbols like emoji 🙂 and test different options. And the only option I see now it's base64, because it can be passed as URL param.

**Comment by evermake** [comment]
Firstly we should understand the specification of URL strings, how browser process them and what we can do.
